entrada = input('Digite algo ')
print('O tipo primitivo desse valor é', type(entrada))
print("Só tem espaços?", entrada.isspace())
print('É um número?', entrada.isnumeric())
print('É alfabético?', entrada.isalpha())
print('É alfanumérico? ', entrada.isalnum())
print('Está somente em maiusculas? ', entrada.isupper())
print('Está somente em minúsculas?', entrada.islower()
)
print('Esta capitalizada?', entrada.istitle())