primeiro=int(input("Primeiro número: "))
segundo=int(input("Segundo número: "))
soma= int(primeiro)+ int(segundo)
#print('A soma é: ', str(soma))
print('A soma entre {0} e {1} vale {2}'.format(primeiro,segundo,soma))